Repository Vladacdc/TransIT.API, pull requests merged in 2019-08, with the labels that each got.

#30 Add LinqKit and use it in repositories
  TransIT.API/EndpointFilters/OnException/DataTableFilterExceptionFilterAttribute.cs
  TransIT.BLL/DTOs/DataTableRequestDTO.cs
  TransIT.BLL/Services/FilterService.cs
  TransIT.BLL/Services/ImplementedServices/ActionTypeService.cs
  TransIT.DAL/Models/Entities/User.cs
  TransIT.DAL/Repositories/ImplementedRepositories/ActionTypeRepository.cs
  TransIT.DAL/Repositories/ImplementedRepositories/BillRepository.cs
  TransIT.DAL/Repositories/ImplementedRepositories/CountryRepository.cs
  TransIT.DAL/Repositories/ImplementedRepositories/CurrencyRepository.cs
  TransIT.DAL/Repositories/ImplementedRepositories/DocumentRepository.cs
  TransIT.DAL/Repositories/ImplementedRepositories/EmployeeRepository.cs
  TransIT.DAL/Repositories/ImplementedRepositories/IssueLogRepository.cs
  TransIT.DAL/Repositories/ImplementedRepositories/IssueRepository.cs
  TransIT.DAL/Repositories/ImplementedRepositories/LocationRepository.cs
  TransIT.DAL/Repositories/ImplementedRepositories/MalfunctionGroupRepository.cs
  TransIT.DAL/Repositories/ImplementedRepositories/MalfunctionRepository.cs
  TransIT.DAL/Repositories/ImplementedRepositories/MalfunctionSubgroupRepository.cs
  TransIT.DAL/Repositories/ImplementedRepositories/PostRepository.cs
  TransIT.DAL/Repositories/ImplementedRepositories/StateRepository.cs
  TransIT.DAL/Repositories/ImplementedRepositories/SupplierRepository.cs
  TransIT.DAL/Repositories/ImplementedRepositories/TransitionRepository.cs
  TransIT.DAL/Repositories/ImplementedRepositories/UserQueryRepository.cs
  TransIT.DAL/Repositories/ImplementedRepositories/VehicleRepository.cs
  TransIT.DAL/Repositories/ImplementedRepositories/VehicleTypeRepository.cs
  TransIT.DAL/TransIT.DAL.csproj
Labels: enhancement

#31 Add more information about error on server
  TransIT.API/EndpointFilters/OnException/ApiExceptionFilterAttribute.cs
  TransIT.API/EndpointFilters/OnException/DataTableFilterExceptionFilterAttribute.cs
  TransIT.API/EndpointFilters/OnException/DeleteExceptionFilterAttribute.cs
  TransIT.API/EndpointFilters/OnException/UpdateExceptionFilterAttribute.cs
  TransIT.BLL/DTOs/DataTableRequestDTO.cs
  TransIT.BLL/DTOs/DataTableResponseDTO.cs
  TransIT.BLL/DTOs/ExtendedErrorDTO.cs
Labels: bug

#32 fixed FilterHelper and IssueLogService
  TransIT.BLL/Helpers/FilterProcessingHelper.cs
  TransIT.BLL/Services/FilterService.cs
  TransIT.BLL/Services/ImplementedServices/IssueLogService.cs
Labels: bug

#36 TNT-788
  TransIT.API/Controllers/IssueController.cs
  TransIT.BLL/DTOs/DataTableRequestDTO.cs
  TransIT.BLL/Services/ImplementedServices/UserService.cs
  TransIT.BLL/Services/Interfaces/IUserService.cs
Labels: bug

#41 Updated length of supplier names
  TransIT.DAL/Models/EntityConfiguration/SupplierConfiguration.cs
Labels: invalid

#44 Employee-User attachment
  TransIT.API/Controllers/EmployeeController.cs
  TransIT.API/Controllers/UserController.cs
  TransIT.API/EndpointFilters/OnException/DataTableFilterExceptionFilterAttribute.cs
  TransIT.API/EndpointFilters/OnException/DeleteExceptionFilterAttribute.cs
  TransIT.API/EndpointFilters/OnException/UpdateExceptionFilterAttribute.cs
  TransIT.API/TransIT.API.csproj
  TransIT.BLL/DTOs/DataTableRequestDTO.cs
  TransIT.BLL/DTOs/EmployeeDTO.cs
  TransIT.BLL/DTOs/UserDTO.cs
  TransIT.BLL/Mappings/UserProfile.cs
  TransIT.BLL/Services/ImplementedServices/BillService.cs
  TransIT.BLL/Services/ImplementedServices/CountryService.cs
  TransIT.BLL/Services/ImplementedServices/CurrencyService.cs
  TransIT.BLL/Services/ImplementedServices/EmployeeService.cs
  TransIT.BLL/Services/ImplementedServices/IssueLogService.cs
  TransIT.BLL/Services/ImplementedServices/IssueService.cs
  TransIT.BLL/Services/ImplementedServices/LocationService.cs
  TransIT.BLL/Services/ImplementedServices/MalfunctionGroupService.cs
  TransIT.BLL/Services/ImplementedServices/MalfunctionService.cs
  TransIT.BLL/Services/ImplementedServices/MalfunctionSubgroupService.cs
  TransIT.BLL/Services/ImplementedServices/PostService.cs
  TransIT.BLL/Services/ImplementedServices/StateService.cs
  TransIT.BLL/Services/ImplementedServices/SupplierService.cs
  TransIT.BLL/Services/ImplementedServices/TransitionService.cs
  TransIT.BLL/Services/ImplementedServices/UserService.cs
  TransIT.BLL/Services/ImplementedServices/VehicleService.cs
  TransIT.BLL/Services/ImplementedServices/VehicleTypeService.cs
  TransIT.BLL/Services/Interfaces/IEmployeeService.cs
  TransIT.DAL/Models/Entities/Employee.cs
  TransIT.DAL/Models/Entities/User.cs
  TransIT.DAL/Models/EntityConfiguration/EmployeeConfiguration.cs
  TransIT.DAL/Repositories/BaseRepository.cs
  TransIT.DAL/Repositories/IBaseRepository.cs
  TransIT.DAL/Repositories/ImplementedRepositories/EmployeeRepository.cs
  TransIT.DAL/Repositories/ImplementedRepositories/UserQueryRepository.cs
  TransIT.DAL/Repositories/InterfacesRepositories/IUserRepository.cs
  TransIT.Tests/Repository/EmployeeRepositoryTests.cs
  TransIT.Tests/ServiceTests/AuthServiceTests.cs
  TransIT.Tests/ServiceTests/EmployeeServiceTests.cs
  TransIT.Tests/ServiceTests/UserServiceTests.cs
  TransIT.Tests/XUnitFixture/MapperFixture.cs
  TransIT.Tests/XUnitFixture/UnitOfWorkFixture.cs
Labels: feature

#47 fixing issues with Enginner and Register
  TransIT.API/Controllers/IssueController.cs
  TransIT.BLL/Mappings/IssueProfile.cs
  TransIT.BLL/Services/ImplementedServices/IssueService.cs
Labels: bug

#49 Add Units & Manufacturers
  TransIT.API/Controllers/ManufacturerController.cs
  TransIT.API/Controllers/UnitController.cs
  TransIT.BLL/ConfigureBLLExtension.cs
  TransIT.BLL/DTOs/ManufacturerDTO.cs
  TransIT.BLL/DTOs/UnitDTO.cs
  TransIT.BLL/Factories/FilterServiceFactory.cs
  TransIT.BLL/Factories/IFilterServiceFactory.cs
  TransIT.BLL/Factories/IServiceFactory.cs
  TransIT.BLL/Factories/ServiceFactory.cs
  TransIT.BLL/Mappings/ManufacturerProfile.cs
  TransIT.BLL/Mappings/UnitProfile.cs
  TransIT.BLL/Services/FilterServices/ManufacturerFilterService.cs
  TransIT.BLL/Services/FilterServices/UnitFilterService.cs
  TransIT.BLL/Services/ImplementedServices/ManufacturerService.cs
  TransIT.BLL/Services/ImplementedServices/UnitService.cs
  TransIT.BLL/Services/Interfaces/IManufacturerService.cs
  TransIT.BLL/Services/Interfaces/IUnitService.cs
  TransIT.BLL/Validations/ManufacturerValidator.cs
  TransIT.BLL/Validations/UnitValidator.cs
  TransIT.DAL/ConfigureDALExtension.cs
  TransIT.DAL/Models/Entities/Manufacturer.cs
  TransIT.DAL/Models/Entities/Unit.cs
  TransIT.DAL/Models/Entities/User.cs
  TransIT.DAL/Models/EntityConfiguration/ManufacturerConfiguration.cs
  TransIT.DAL/Models/EntityConfiguration/UnitConfiguration.cs
  TransIT.DAL/Models/TransITDBContext.cs
  TransIT.DAL/Repositories/ImplementedRepositories/ManufacturerRepository.cs
  TransIT.DAL/Repositories/ImplementedRepositories/UnitRepository.cs
  TransIT.DAL/Repositories/InterfacesRepositories/IManufacturerRepository.cs
  TransIT.DAL/Repositories/InterfacesRepositories/IUnitRepository.cs
  TransIT.DAL/UnitOfWork/IUnitOfWork.cs
  TransIT.DAL/UnitOfWork/UnitOfWork.cs
  TransIT.Tests/XUnitFixture/UnitOfWorkFixture.cs
Labels: feature

#51 Fixed bug with creating issue and bug with changing issue state, assigned to, deadline
  TransIT.BLL/Mappings/IssueProfile.cs
  TransIT.BLL/Services/ImplementedServices/IssueLogService.cs
  TransIT.BLL/Services/ImplementedServices/IssueService.cs
Labels: bug

#52 Added Tests to Unit & Manufacturer
  TransIT.BLL/Services/ImplementedServices/ManufacturerService.cs
  TransIT.BLL/Services/ImplementedServices/UnitService.cs
  TransIT.DAL/Repositories/ImplementedRepositories/ManufacturerRepository.cs
  TransIT.DAL/Repositories/ImplementedRepositories/UnitRepository.cs
  TransIT.Tests/Helper/TestSetUpHelper.cs
  TransIT.Tests/Repository/EmployeeRepositoryTests.cs
  TransIT.Tests/Repository/ManufacturerRepositoryTests.cs
  TransIT.Tests/Repository/UnitRepositoryTests.cs
  TransIT.Tests/ServiceTests/AuthServiceTests.cs
  TransIT.Tests/ServiceTests/EmployeeServiceTests.cs
  TransIT.Tests/ServiceTests/ManufacturerServiceTests.cs
  TransIT.Tests/ServiceTests/UnitServiceTests.cs
  TransIT.Tests/ServiceTests/UserServiceTests.cs
  TransIT.Tests/XUnitFixture/MapperFixture.cs
Labels: enhancement
